services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile.production
    expose:
      - "3000"
    container_name: travel-server
  
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile.production
    ports:
      - 80:80
    container_name: travel-frontend
    depends_on:
      - backend
