name: Manual CI

on:
  push

jobs:
  frontend:
    runs-on: ubuntu-latest
      steps:
        -uses: actions/checkout@v4

        -uses: actions/setup-node@v4
          -with:
            node-version: 20
            cache: npm
            cahe-dependency-path: frontend/package-lock.json
        
        -working-directory: frontend
          run: npm CI
        
        -working-directory: frontend
          run: npm test